### ISSUE TITLE
Dedicated Server Crash

### ISSUE THREAD

**Issue by Darkhax** [LegendaryGeek/World-of-Wonder#6]
Version: 1.0.2
```
[22May2020 00:00:32.261] [modloading-worker-3/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Failed to create mod instance. ModID: worldofwonder, class net.msrandom.worldofwonder.WorldOfWonder
java.lang.NoClassDefFoundError: net/minecraft/client/renderer/entity/model/BipedModel
	at net.msrandom.worldofwonder.item.WonderItems.<clinit>(WonderItems.java:12) ~[?:?]
	at net.msrandom.worldofwonder.block.WonderBlocks.add(WonderBlocks.java:49) ~[?:?]
	at net.msrandom.worldofwonder.block.WonderBlocks.add(WonderBlocks.java:44) ~[?:?]
	at net.msrandom.worldofwonder.block.WonderBlocks.<clinit>(WonderBlocks.java:18) ~[?:?]
	at net.msrandom.worldofwonder.WorldOfWonder.<init>(WorldOfWonder.java:28) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_252]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_252]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_252]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_252]
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_252]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:131) ~[?:31.2]
	at java.util.function.Consumer.lambda$andThen$0(Consumer.java:65) ~[?:1.8.0_252]
	at java.util.function.Consumer.lambda$andThen$0(Consumer.java:65) ~[?:1.8.0_252]
	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:112) ~[?:?]
	at net.minecraftforge.fml.ModList.lambda$null$10(ModList.java:135) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) [?:1.8.0_252]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) [?:1.8.0_252]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) [?:1.8.0_252]
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290) [?:1.8.0_252]
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731) [?:1.8.0_252]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_252]
	at java.util.concurrent.ForkJoinPool$WorkQueue.execLocalTasks(ForkJoinPool.java:1040) [?:1.8.0_252]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1058) [?:1.8.0_252]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_252]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_252]
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.entity.model.BipedModel
	at java.lang.ClassLoader.findClass(ClassLoader.java:523) ~[?:1.8.0_252]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_252]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:101) ~[modlauncher-5.1.0.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_252]
	... 25 more
```

**Comment by MsRandom** [comment]
Fixed.
